apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: demo-application
spec:
  project: default
  destination:
    name: ""
    namespace: dev
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://raw.githubusercontent.com/ChrisDevOpsOrg/helm-charts/main/"
      targetRevision: 0.1.5
      chart: demo
      helm:
        valueFiles:
          - $values/helm-values/develop/app-values.yaml
          - $values/helm-values/develop/infra-values.yaml
    - repoURL: "git@github.com:ChrisDevOpsOrg/argocd-demo.git"
      targetRevision: 1.0.0
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
#    - kind: ConfigMap
#      jqPathExpressions:
#        - '.data["config.yaml"].auth'
  revisionHistoryLimit: 10