---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo
  namespace: argocd
spec:
  description: "Demo project to test role binding and permission restriction"
  # Allow manifest to deploy from any repos
  sourceRepos:
    - '*'

  # Only permit application to deploy to a particular namespace in the particular cluster
  # Destination clusters can be identified by 'server', 'name', or both
  destinations:
    - namespace: 'dev'
      server: 'in-cluster'
    - namespace: 'qa'
      server: 'qa-cluster'
  # Deny all cluster-scoped resources from being created, expect for Namespace
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'

  clusterResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
    - group: ''
      kind: ClusterRoleBinding

  # Deny all namespaced-scoped resources from being created, expect for Deployment,StatefulSet, DaemonSet.
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet

  # Enable namespace orphaned resource monitoring
  orphanedResources:
    warn: false

  roles:
    # A role with provides read-only access to all applications in the project
    - name: read-only
      description: Read-only privileges to demo project
      policies:
        - p, proj:demo:read-only, applications, get, demo/*, allow
      groups:
        - demo-group

    # A role with providers sync privileges to only gustbook application.
    # e.g. to provide sync privileges to a CI system
    - name: ci-role
      description: "Sync privileges for gustbook-dev"
      policies:
        - p, proj:demo:ci-role, applications, sync, demo/gustbook-dev, allow

      # NOTE: JWT tokens can only be generated by the API server and the token is not persisted
      # anywhere by Argo CD. It can be prematurely revoked by removing the entry from this list
      jwtTokens:
        - iat: 12345678

  syncWindows:
    - kind: allow
      schedule: '10 1 * * *'
      duration: 1h
      applications:
        - '*-dev'
      manualSync: true
    - kind: deny
      schedule: '0 22 * * *'
      duration: 1h
      applications:
        - '*-prod'
      manualSync: true
    - kind: deny
      schedule: '0 22 * * *'
      duration: 1h
      clusters:
        - in-cluster
        - qa-cluster





