apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: postgresql
    helm:
      parameters:
      - name: auth.password
        value: postgresqladmin
      - name: auth.postgresPassword
        value: postgresqladmin
      - name: auth.username
        value: postgres
      - name: auth.database
        value: keycloak
      - name: primary.service.type
        value: LoadBalancer
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.2
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true

