apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://192.168.56.10
  oidc.config: |
    name: Keycloak
    issuer: http://192.168.56.12:8080/realms/master
    clientID: argocd
    clientSecret: PBDOXuruqHHKyyDolsvtuPtXI5pZqyYK 
    requestedScopes: ["openid", "profile", "email", "groups"]
