name: Test Job On Pull Request
 
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
 
permissions:
  contents: read
  actions: read
  security-events: write
 
jobs:
  validate:
    name: Test Validate PR
    runs-on: ubuntu-latest
    container:
      image: node:22.15.0-alpine
      options: --user root
    steps:
      - name: Install git and bash
        run: |
          apk add --no-cache git bash
 
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Enable Corepack
        run: |
          echo "This is another test job run on Pull Request"
