name: Test Job On Pull Request
 
on:
  push:
    branches:
      - develop
 
permissions:
  contents: read
  actions: read
  security-events: write
 
jobs:
  validate:
    name: Test On Push
    runs-on: ubuntu-latest
    container:
      image: node:22.15.0-alpine
      options: --user root
    steps:
      - name: Install git and bash
        run: |
          apk add --no-cache git bash
 
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Enable Corepack
        run: |
          echo "This is  test job run on Push"
