# This is a basic workflow to help you get started with Actions

name: Update Image Tag

on:
  repository_dispatch:
    type: ["update-image-tag"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Image Tag
        run: |
          echo ${{ github.event.client_payload.imageName }}
          echo ${{ github.event.client_payload.Tag }}
